### PR TITLE
Add migrations, AR associations and enums to models

### PR DESCRIPTION
**Pull request by litobot**
It says it all in the title.

### CODE REVIEW

**Comment by JCL461437** [comment]
Looks great! Thanks for doing that Lito

**Review by JCL461437 — APPROVED** [review]
Awesome work setting up the migrations and model associations.

**Review by CoryBretsch — APPROVED** [review]
Looks solid!

written note so we dont forget - we will need to add data validations in models, and write tests for relationships and validations.

**Comment by JCL461437** [comment]
Great call Cory, I am happy to do that

**Pull request merged**
